#!/usr/bin/env python3
"""Build a Markdown summary of fc_n10 paper-grade metrics across all runs.

Reads:
  - logs/v3fix_full/fc_n10_threshold_aware.json   (recall@FPR, P@R, F1max)
  - logs/v3fix_full/verify_forecast_r1r2.log      (paper-grade lead time)
  - outputs/csc_training/<run>_stage2/val_metrics.json  (final state classif)

Writes:
  logs/v3fix_full/fc_n10_summary.md

Re-runs automatically when R25 ckpt appears.
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = ROOT / "logs" / "v3fix_full"

RUNS = {
    "r1": {
        "label": "Run 1 (V1)",
        "ckpt_dir": ROOT / "outputs/csc_training/sglatrack_v3fix_tcn16_stage2",
        "feat": "v1",
        "FCw": 4.0,
    },
    "r2": {
        "label": "Run 2 (V2)",
        "ckpt_dir": ROOT / "outputs/csc_training/sglatrack_run2_scalectx_tcn16_stage2",
        "feat": "v2",
        "FCw": 4.0,
    },
    "r25": {
        "label": "Run 2.5 (V2 + FCw=3.0)",
        "ckpt_dir": ROOT / "outputs/csc_training/sglatrack_r25_fcw3_tcn16_stage2",
        "feat": "v2",
        "FCw": 3.0,
    },
}


def load_json(p: Path) -> dict | list:
    try:
        return json.loads(p.read_text())
    except Exception:
        return {}


def parse_verify_log(path: Path) -> dict[str, dict]:
    """Parse verify_forecast_r1r2.log aggregate section."""
    if not path.exists():
        return {}
    text = path.read_text(errors="ignore")
    out = {}
    for tag in ("R1 (V1)", "R2 (V2)"):
        pat = re.compile(
            rf"\[{re.escape(tag)}\] aggregate over (\d+) onsets[^\n]*\n"
            rf"\s*lead_strict\s+mean=([\d.]+)\s+med=([\d.]+)\s+p25=([\d.]+)\s+p75=([\d.]+)\n"
            rf"\s*lead_any\s+mean=([\d.]+)\s+med=([\d.]+)\n"
            rf"\s*fraction with lead_strict >= 5:\s*([\d.]+)",
            re.MULTILINE,
        )
        m = pat.search(text)
        if m:
            key = "r1" if tag.startswith("R1") else "r2"
            out[key] = {
                "n_onsets": int(m.group(1)),
                "lead_strict_mean": float(m.group(2)),
                "lead_strict_p25": float(m.group(4)),
                "lead_any_mean": float(m.group(6)),
                "frac_ge_5": float(m.group(8)),
            }
    return out


def main():
    thr = load_json(LOG / "fc_n10_threshold_aware.json")
    verify = parse_verify_log(LOG / "verify_forecast_r1r2.log")

    thr_by_dir = {}
    if isinstance(thr, list):
        for r in thr:
            ckpt = Path(r["ckpt"])
            thr_by_dir[ckpt.parent.name] = r

    lines = ["# CSC fc_n10 Forecast Head — Paper-Grade Summary",
             "",
             f"Generated by `tools/build_fc_n10_summary.py`",
             "",
             "## What this measures",
             "",
             "Forecast head `false_confirmed_next_10` predicts whether the tracker will enter "
             "FALSE_CONFIRMED state within the next 10 frames. Operating-point metrics are the "
             "scientifically meaningful ones for proactive control (single-threshold trigger).",
             "",
             "Baseline (random): pos_rate = 2.3% → AUPRC baseline = 0.023.",
             "",
             "## State classification (Stage 2 final val_metrics)",
             "",
             "| Run | feat | FCw | macro_F1 | FC_F1 | FC_prec | FC_recall | fail_AUPRC | fc_n10_AUPRC |",
             "|---|---|---|---|---|---|---|---|---|"]

    for key, cfg in RUNS.items():
        vm_path = cfg["ckpt_dir"] / "val_metrics.json"
        vm = load_json(vm_path)
        if not vm:
            lines.append(f"| {cfg['label']} | {cfg['feat']} | {cfg['FCw']} | — | — | — | — | — | — |")
            continue
        ps = vm.get("derived_per_state", {}).get("FALSE_CONFIRMED", {})
        lines.append(
            f"| {cfg['label']} | {cfg['feat']} | {cfg['FCw']} | "
            f"{vm.get('derived_macro_f1', 0):.4f} | "
            f"{ps.get('f1', 0):.4f} | {ps.get('precision', 0):.4f} | {ps.get('recall', 0):.4f} | "
            f"{vm.get('failure_auprc', 0):.4f} | "
            f"{vm.get('false_confirmed_next_10_auprc', 0):.4f} |"
        )

    lines += ["",
              "## fc_n10 threshold-aware operating points",
              "",
              "Key metric for proactive control: **R@FPR≤3%** (recall at <=3% false alarm rate).",
              "",
              "| Run | feat | R@FPR≤1% | R@FPR≤3% | R@FPR≤5% | P@R50 | P@R70 | P@R85 | F1max |",
              "|---|---|---|---|---|---|---|---|---|"]

    name_map = {
        "sglatrack_v3fix_tcn16_stage2": "r1",
        "sglatrack_run2_scalectx_tcn16_stage2": "r2",
        "sglatrack_r25_fcw3_tcn16_stage2": "r25",
    }

    for key, cfg in RUNS.items():
        target_name = cfg["ckpt_dir"].name
        r = thr_by_dir.get(target_name)
        if r is None:
            lines.append(f"| {cfg['label']} | {cfg['feat']} | — | — | — | — | — | — | — |")
            continue
        lines.append(
            f"| {cfg['label']} | {cfg['feat']} | "
            f"{r['recall_at_fpr_01']:.3f} | **{r['recall_at_fpr_03']:.3f}** | "
            f"{r['recall_at_fpr_05']:.3f} | "
            f"{r['precision_at_recall_50']:.3f} | {r['precision_at_recall_70']:.3f} | "
            f"{r['precision_at_recall_85']:.3f} | {r['best_f1']:.3f} |"
        )

    lines += ["",
              "## Paper-grade lead time (verify_forecast_heads.py, 110 FC onsets)",
              "",
              "Measures how many frames AHEAD of the FC onset the forecast head fires.",
              "**Higher = earlier warning. Threshold = 0.50.**",
              "",
              "| Run | n_onsets | mean lead_strict | p25 lead_strict | mean lead_any | frac(lead≥5) |",
              "|---|---|---|---|---|---|"]

    for tag in ("r1", "r2"):
        v = verify.get(tag)
        if v is None:
            lines.append(f"| {RUNS[tag]['label']} | — | — | — | — | — |")
            continue
        lines.append(
            f"| {RUNS[tag]['label']} | {v['n_onsets']} | "
            f"{v['lead_strict_mean']:.2f} | {v['lead_strict_p25']:.2f} | "
            f"{v['lead_any_mean']:.2f} | **{v['frac_ge_5']:.3f}** |"
        )

    lines += ["",
              "## Reading guide",
              "",
              "**For control mode** (decide when to freeze template, expand search, etc.):",
              "- Pick operating point by FPR budget: `R@FPR≤3%` is sensible for production.",
              "- `P@R50 ≥ 0.65` means <35% false freezes at 50% catch rate — usable.",
              "- Higher `frac(lead≥5)` = more useful lead time (less reactive, more proactive).",
              "",
              "**Tradeoffs observed:**",
              "- V2 features lift `R@FPR≤3%` and `P@R50` (better operating curve).",
              "- V1 features give longer lead time on confirmed FC onsets (calibration effect).",
              "- Lower FCw (3.0 vs 4.0) is expected to lift precision at small recall cost.",
              ""]

    out = LOG / "fc_n10_summary.md"
    out.write_text("\n".join(lines))
    print(f"→ {out}")


if __name__ == "__main__":
    sys.exit(main())
