#!/usr/bin/env python
"""CSC-v4 module A5 — offline counterfactual action-gain labels (the action-utility
supervision target for the V4 model's `action_utility` head).

For a PASSIVE run dir (predictions/ + states/ + telemetry/, as produced by
tools/run_with_csc.py) we walk each sequence and, for every frame inside a
loss/risk WINDOW, ESTIMATE what each control Action (v4.types.Action) would have
done to the NEXT-frame IoU vs the passive baseline, using only stored
predictions + ground-truth + telemetry. We emit, per windowed frame:

    action_gain[action_name] = ΔIoU  (estimated next-frame IoU minus passive)
    best_action               = argmax-gain action name
    recoverable_by_bridge     = motion_bridge gain >= recover_margin
    recoverable_by_relocate   = relocate gain      >= recover_margin
    needs_global_search       = only global_search clears recover_margin
    do_not_act                = every action gain <= 0 (HOLD is best)
    template_update_safe      = passive box still on target (safe to refresh)

────────────────────────────────────────────────────────────────────────────
APPROXIMATION (the whole sweep is offline; NO tracker is re-run — see A5 in
csc_lib/csc/v4/CONTRACT.md, "You may APPROXIMATE the sweep cheaply offline
WITHOUT re-running the tracker"). A full tracker-in-the-loop sweep is future
work. Every approximate quantity below is marked `# APPROX`. The stored
telemetry does NOT contain candidate pixel boxes — only scalar score-map stats
(sm_n_secondary, sm_local_top2_ratio, sm_peak_distance, ...) — so RELOCATE and
GLOBAL_SEARCH are modelled from those scalars + a GT-derived "best achievable"
box rather than from real candidate coordinates. These are SUPERVISION
PROXIES, not measured tracker outputs, and must be regenerated by a real sweep
before any headline claim.

Per-action next-frame-IoU proxy (all `# APPROX`):
  HOLD            : passive next-frame IoU (the box the tracker actually drew).
  MOTION_BRIDGE   : IoU(extrapolated-centre box, GT_next). The centre is
                    last_good_centre + EMA_velocity * frames_since_loss with the
                    last-good size, mirroring run_with_csc.py's motion_bridge
                    (regularity gate + displacement cap). Smooth motion -> high.
  RELOCATE        : IoU of a "secondary-peak-on-target" box, CREDITED only when
                    telemetry says a usable secondary peak exists
                    (sm_n_secondary>0 OR sm_local_top2_ratio>=relocate_ratio).
                    Proxy box = GT_next-snapped box at the passive scale (best
                    case a real secondary peak could achieve), else passive box.
  WIDEN           : passive box nudged a fraction (widen_frac) toward the
                    GT-snapped box — a wider crop recovers a target that drifted
                    just outside the current crop; bounded, never worse than HOLD.
  GLOBAL_SEARCH   : GT-snapped-box IoU (a budgeted full re-detector can in
                    principle re-acquire anywhere) — credited only on a genuine
                    loss (passive IoU < loss_iou) so easy frames don't reward it.
  TEMPLATE_UPDATE : position-neutral this frame == HOLD IoU (it changes future
                    template quality, not next-frame localisation).
  FREEZE          : position-neutral this frame == HOLD IoU.
────────────────────────────────────────────────────────────────────────────

CLI:
  --passive_dir <run>   passive run dir (has predictions/ states/ telemetry/)
  --dataset uav123      dataset name for la_smoke.build_index (default uav123)
  --out <path.jsonl>    output JSONL (one record per windowed frame)
  --seqs a b ...        restrict to these sequences (optional)
  --selftest            run a tiny synthetic example with NO dataset; assert
                        the output schema; write nothing unless --out given.

Reuses tools/la_smoke.py loaders (build_index, seq_iou, gt_array, read_preds).
Read-only over the run dir; offline SOT benchmark; CPU-only; additive.
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

import numpy as np

# --- sys.path mirror of tools/la_smoke.py (canonical lib path) -------
PROJECT_ROOT = Path(__file__).resolve().parents[1]
for _p in (PROJECT_ROOT / "src", PROJECT_ROOT, PROJECT_ROOT / "tools"):
    sys.path.insert(0, str(_p))

# v4 shared types are the single source of truth for the action space.
from csc_lib.csc.v4.v4types import ACTION_NAMES, Action  # noqa: E402

# Single-box IoU helper (pure numpy, xywh) — reused, not reimplemented.
from csc_lib.eval.custom_metrics.bbox import iou_xywh  # noqa: E402


# ---------------------------------------------------------------------------
# Config (all thresholds are args with documented defaults).
# ---------------------------------------------------------------------------
@dataclass
class SweepConfig:
    """Thresholds governing the window, the per-action proxies, and the flags."""
    loss_iou: float = 0.20          # passive IoU below this == "in a loss"
    risk_iou: float = 0.50          # passive IoU below this == "at risk" (window edge)
    pre_window: int = 3             # frames BEFORE a loss/risk frame to include (lead time)
    recover_margin: float = 0.05    # ΔIoU a recovery action must clear to count
    relocate_ratio: float = 0.30    # min sm_local_top2_ratio for a usable secondary peak
    widen_frac: float = 0.40        # fraction of (GT-snap − passive) IoU credited to widen
    vel_ema: float = 0.50           # EMA factor for the bridge velocity (matches run_with_csc default)
    bridge_max_resid_ratio: float = 1.0   # regularity gate: vel_resid/scale must be <= this to bridge
    bridge_max_disp: float = 4.0    # bridge displacement cap, in multiples of target scale (0=off)
    template_safe_iou: float = 0.50  # passive IoU above this == template refresh safe


# ---------------------------------------------------------------------------
# Telemetry loading (mirrors la_smoke's per-line json walk; tolerant of gaps).
# ---------------------------------------------------------------------------
def read_telemetry(path: Path, n: int) -> list[dict]:
    """Return a length-n list of telemetry dicts indexed by frame_idx.

    Missing frames -> empty dict. Mirrors how la_smoke reads states JSONL.
    """
    rows: list[dict] = [dict() for _ in range(n)]
    if not path.exists():
        return rows
    for ln in open(path):
        ln = ln.strip()
        if not ln:
            continue
        d = json.loads(ln)
        t = int(d.get("frame_idx", -1))
        if 0 <= t < n:
            rows[t] = d
    return rows


def read_states(path: Path, n: int) -> list[dict]:
    """Length-n list of states dicts (derived_state, forecast probs)."""
    return read_telemetry(path, n)  # same JSONL-by-frame_idx layout


def _f(d: dict, key: str, default: float = 0.0) -> float:
    """Safe float fetch (None / missing -> default)."""
    v = d.get(key, default)
    if v is None:
        return default
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def _center(b) -> tuple[float, float]:
    return float(b[0]) + float(b[2]) / 2.0, float(b[1]) + float(b[3]) / 2.0


def _gt_valid(g) -> bool:
    """la_smoke.gt_array encodes invalid/absent GT as [0,0,0,0]."""
    return float(g[2]) > 0.0 and float(g[3]) > 0.0


# ---------------------------------------------------------------------------
# The core approximation: per-frame ΔIoU for every Action.
# ---------------------------------------------------------------------------
def estimate_action_gains(
    t: int,
    pr: np.ndarray,            # (T,4) passive predictions, xywh
    gt: np.ndarray,            # (T,4) ground truth, xywh ([0,0,0,0] == invalid)
    tel: list[dict],           # length-T telemetry dicts
    states: list[dict],        # length-T states dicts
    bridge_center: Optional[tuple[float, float]],
    bridge_vel: tuple[float, float],
    vel_resid: float,
    frames_since_loss: int,
    cfg: SweepConfig,
) -> tuple[dict[str, float], float, float]:
    """Estimate ΔIoU (vs passive) for each action at the transition t -> t+1.

    Returns (action_gain dict over ACTION_NAMES, passive_iou_next, gtsnap_iou_next).
    All branches are `# APPROX` (offline, tracker not re-run).
    """
    nxt = t + 1
    g_next = gt[nxt]
    if not _gt_valid(g_next):
        # No GT to score the next frame against -> every action is a no-op (0 gain).
        return {name: 0.0 for name in ACTION_NAMES}, float("nan"), float("nan")

    # --- HOLD == passive next-frame IoU (what the tracker actually produced). # APPROX
    passive_iou = iou_xywh(pr[nxt], g_next)

    # The "best achievable" box this frame: GT centre at the PASSIVE scale (we
    # cannot know the true scale a re-detector would pick, so we keep the last
    # passive size — a conservative, scale-preserving snap).            # APPROX
    pw, ph = float(pr[nxt][2]), float(pr[nxt][3])
    if pw <= 0 or ph <= 0:                      # passive box collapsed -> fall back to GT scale
        pw, ph = float(g_next[2]), float(g_next[3])
    gcx, gcy = _center(g_next)
    gtsnap_box = (gcx - pw / 2.0, gcy - ph / 2.0, pw, ph)
    gtsnap_iou = iou_xywh(gtsnap_box, g_next)   # IoU of a perfectly-centred passive-scale box

    tnow = tel[t]
    snow = states[t]

    # --- MOTION_BRIDGE: extrapolate last-good centre by EMA velocity.    # APPROX
    # Mirrors run_with_csc.py: centre = last_good + vel * frames_since_loss, with
    # a regularity gate (vel_resid/scale) and a displacement cap. If the gate is
    # shut or there's no anchor, bridging holds (gain 0).
    bridge_iou = passive_iou
    if bridge_center is not None and frames_since_loss >= 1:
        scale = max(1.0, (pw * ph) ** 0.5)
        if vel_resid / scale <= cfg.bridge_max_resid_ratio:
            dx = bridge_vel[0] * frames_since_loss
            dy = bridge_vel[1] * frames_since_loss
            if cfg.bridge_max_disp > 0:
                mag = (dx * dx + dy * dy) ** 0.5
                cap = cfg.bridge_max_disp * scale
                if mag > cap and mag > 1e-6:
                    r = cap / mag
                    dx *= r
                    dy *= r
            bcx = bridge_center[0] + dx
            bcy = bridge_center[1] + dy
            bridge_box = (bcx - pw / 2.0, bcy - ph / 2.0, pw, ph)
            bridge_iou = iou_xywh(bridge_box, g_next)

    # --- RELOCATE: jump to a secondary score-map peak.                   # APPROX
    # No candidate pixel boxes are stored, so we credit relocate ONLY when the
    # telemetry says a usable secondary peak exists, and model its best case as
    # the GT-snapped box (a real secondary peak that happens to sit on target).
    # Otherwise relocate would just keep the (wrong) passive box.
    n_secondary = _f(tnow, "sm_n_secondary", 0.0)
    top2_ratio = _f(tnow, "sm_local_top2_ratio", 0.0)
    has_secondary = (n_secondary > 0.0) or (top2_ratio >= cfg.relocate_ratio)
    relocate_iou = gtsnap_iou if has_secondary else passive_iou

    # --- WIDEN: a wider crop recovers a target that drifted just outside it. # APPROX
    # Modelled as a bounded partial move from passive toward the GT-snap IoU; a
    # wider search never localises better than a perfectly-centred box, and is
    # never worse than holding.
    widen_iou = passive_iou + cfg.widen_frac * max(0.0, gtsnap_iou - passive_iou)

    # --- GLOBAL_SEARCH: budgeted full re-detector can re-acquire anywhere. # APPROX
    # Credited with the GT-snap IoU, but only on a genuine loss; on a healthy
    # frame a global search is wasted (and risky), so it just holds.
    is_loss = passive_iou < cfg.loss_iou
    global_iou = gtsnap_iou if is_loss else passive_iou

    # --- TEMPLATE_UPDATE / FREEZE: position-neutral THIS frame.          # APPROX
    # They change the future template, not the next-frame localisation, so their
    # one-step ΔIoU is 0 (== HOLD). template_update_safe (below) is the real
    # signal for whether a refresh is safe.
    template_iou = passive_iou
    freeze_iou = passive_iou

    iou_by_action = {
        Action.HOLD.name.lower(): passive_iou,
        Action.MOTION_BRIDGE.name.lower(): bridge_iou,
        Action.RELOCATE.name.lower(): relocate_iou,
        Action.WIDEN.name.lower(): widen_iou,
        Action.GLOBAL_SEARCH.name.lower(): global_iou,
        Action.TEMPLATE_UPDATE.name.lower(): template_iou,
        Action.FREEZE.name.lower(): freeze_iou,
    }
    # ΔIoU vs the passive (HOLD) baseline.
    gain = {name: float(iou_by_action[name] - passive_iou) for name in ACTION_NAMES}
    return gain, float(passive_iou), float(gtsnap_iou)


# ---------------------------------------------------------------------------
# Sequence-level sweep.
# ---------------------------------------------------------------------------
def sweep_sequence(
    name: str,
    pr: np.ndarray,
    gt: np.ndarray,
    tel: list[dict],
    states: list[dict],
    cfg: SweepConfig,
) -> list[dict]:
    """Walk a sequence, maintain bridge state on CC frames, emit windowed records.

    Window = any frame whose passive IoU < risk_iou (loss or at-risk), plus the
    `pre_window` frames before it (lead time). Bridge bookkeeping (last-good
    centre, EMA velocity, regularity residual) is updated on CC frames exactly
    like the runtime motion_bridge, so MOTION_BRIDGE gains use a faithful
    velocity model.
    """
    n = min(len(pr), len(gt), len(tel), len(states))
    if n < 2:
        return []

    # Per-frame passive IoU (used to define the window + the loss state).
    passive_iou = np.array(
        [iou_xywh(pr[i], gt[i]) if _gt_valid(gt[i]) else np.nan for i in range(n)],
        dtype=float,
    )

    # Mark windowed frames: at-risk (or its lead-in). We score t -> t+1, so the
    # last frame (n-1) can never be a source frame.
    in_window = np.zeros(n, dtype=bool)
    for i in range(n):
        if np.isfinite(passive_iou[i]) and passive_iou[i] < cfg.risk_iou:
            lo = max(0, i - cfg.pre_window)
            in_window[lo:i + 1] = True

    records: list[dict] = []
    # Bridge state (mirrors run_with_csc.py motion_bridge bookkeeping). # APPROX
    bridge_center: Optional[tuple[float, float]] = None
    bridge_size: Optional[tuple[float, float]] = None
    bridge_vel = (0.0, 0.0)
    vel_resid = 1e9          # "unset" sentinel (matches run_with_csc.py)
    frames_since_loss = 0

    for t in range(n - 1):
        st = states[t]
        ds = st.get("derived_state")
        ds = int(ds) if ds is not None else None

        # --- update bridge model on CC frames (derived_state == 0). # APPROX
        if ds == 0:
            cx, cy = _center(pr[t])
            if bridge_center is not None:
                ivx = cx - bridge_center[0]
                ivy = cy - bridge_center[1]
                resid = ((ivx - bridge_vel[0]) ** 2 + (ivy - bridge_vel[1]) ** 2) ** 0.5
                a = cfg.vel_ema
                vel_resid = resid if vel_resid >= 1e8 else (a * vel_resid + (1 - a) * resid)
                bridge_vel = (a * bridge_vel[0] + (1 - a) * ivx,
                              a * bridge_vel[1] + (1 - a) * ivy)
            bridge_center = (cx, cy)
            bridge_size = (float(pr[t][2]), float(pr[t][3]))
            frames_since_loss = 0
        else:
            frames_since_loss += 1

        if not in_window[t]:
            continue

        gain, p_iou, gtsnap_iou = estimate_action_gains(
            t, pr, gt, tel, states,
            bridge_center=bridge_center,
            bridge_vel=bridge_vel,
            vel_resid=vel_resid,
            frames_since_loss=frames_since_loss,
            cfg=cfg,
        )
        if not np.isfinite(p_iou):    # no GT next frame -> skip (nothing to learn)
            continue

        # --- derived flags from the gains. ---
        best_action = max(ACTION_NAMES, key=lambda a: gain[a])
        best_gain = gain[best_action]
        bridge_g = gain[Action.MOTION_BRIDGE.name.lower()]
        relocate_g = gain[Action.RELOCATE.name.lower()]
        global_g = gain[Action.GLOBAL_SEARCH.name.lower()]

        recoverable_by_bridge = bool(bridge_g >= cfg.recover_margin)
        recoverable_by_relocate = bool(relocate_g >= cfg.recover_margin)
        # needs_global_search: only global_search clears the margin among the
        # recovery actions (bridge + relocate both fall short, global wins).
        needs_global_search = bool(
            global_g >= cfg.recover_margin
            and not recoverable_by_bridge
            and not recoverable_by_relocate
        )
        # do_not_act: nothing beats holding (every gain <= 0).
        do_not_act = bool(best_gain <= 0.0)
        # template_update_safe: the passive box is still on target. # APPROX
        template_update_safe = bool(p_iou >= cfg.template_safe_iou)

        records.append({
            "seq": name,
            "frame_idx": int(t),
            "next_frame_idx": int(t + 1),
            "passive_iou": round(p_iou, 6),
            "passive_iou_next": round(p_iou, 6),     # alias: IoU of HOLD at t->t+1
            "gtsnap_iou_next": round(float(gtsnap_iou), 6),
            "derived_state": ds,
            "frames_since_loss": int(frames_since_loss),
            "action_gain": {k: round(v, 6) for k, v in gain.items()},
            "best_action": best_action,
            "best_gain": round(float(best_gain), 6),
            "recoverable_by_bridge": recoverable_by_bridge,
            "recoverable_by_relocate": recoverable_by_relocate,
            "needs_global_search": needs_global_search,
            "do_not_act": do_not_act,
            "template_update_safe": template_update_safe,
            "approx": True,    # this record is an OFFLINE PROXY, not a tracker re-run
        })
    return records


# ---------------------------------------------------------------------------
# Output schema assertion (shared by --selftest and the real path).
# ---------------------------------------------------------------------------
_REQUIRED_KEYS = (
    "seq", "frame_idx", "next_frame_idx", "passive_iou", "passive_iou_next",
    "gtsnap_iou_next", "derived_state", "frames_since_loss", "action_gain",
    "best_action", "best_gain", "recoverable_by_bridge", "recoverable_by_relocate",
    "needs_global_search", "do_not_act", "template_update_safe", "approx",
)


def assert_record_schema(rec: dict) -> None:
    """Validate one output record against the A5 contract schema."""
    for k in _REQUIRED_KEYS:
        assert k in rec, f"missing key {k!r} in record"
    ag = rec["action_gain"]
    assert isinstance(ag, dict), "action_gain must be a dict"
    assert set(ag.keys()) == set(ACTION_NAMES), (
        f"action_gain keys {sorted(ag.keys())} != ACTION_NAMES {sorted(ACTION_NAMES)}"
    )
    for a, v in ag.items():
        assert isinstance(v, (int, float)) and np.isfinite(v), f"action_gain[{a}]={v!r} not finite"
    assert rec["best_action"] in ACTION_NAMES, f"best_action {rec['best_action']!r} not an action"
    for flag in ("recoverable_by_bridge", "recoverable_by_relocate",
                 "needs_global_search", "do_not_act", "template_update_safe", "approx"):
        assert isinstance(rec[flag], bool), f"{flag} must be bool, got {type(rec[flag])}"
    # HOLD gain is the baseline -> always exactly 0.
    assert abs(ag[Action.HOLD.name.lower()]) < 1e-9, "HOLD gain must be 0 (it is the baseline)"


# ---------------------------------------------------------------------------
# Self-test: a tiny synthetic example, NO dataset, asserts the schema.
# ---------------------------------------------------------------------------
def _selftest(out_path: Optional[Path]) -> int:
    """Synthetic loss episode + assertions. Returns process exit code."""
    print("[selftest] building synthetic sequence (no dataset) ...", file=sys.stderr)
    n = 12
    # GT: target moves smoothly to the right at +10 px/frame.
    gt = np.array([[100.0 + 10.0 * i, 100.0, 40.0, 40.0] for i in range(n)], dtype=float)

    # Passive predictions: tracks well for the first 5 frames (CC), then the box
    # STICKS at frame 5's position (a smooth loss the tracker missed) -> IoU
    # decays to 0 as the true target moves away. A motion-bridge that extrapolates
    # the +10 px/frame velocity should recover the target.
    pr = gt.copy()
    stuck = gt[5].copy()
    for i in range(5, n):
        pr[i] = stuck

    # Telemetry / states by frame_idx. CC (derived_state 0) for 0..4, LA (2) after.
    tel: list[dict] = []
    states: list[dict] = []
    for i in range(n):
        ds = 0 if i < 5 else 2
        tel.append({
            "frame_idx": i,
            "confidence": 0.9 if ds == 0 else 0.2,
            "sm_n_secondary": 0.0,            # no secondary peak -> relocate should NOT be credited
            "sm_local_top2_ratio": 0.0,
            "response_entropy": 1.0 if ds == 0 else 3.0,
        })
        states.append({"frame_idx": i, "derived_state": ds})

    cfg = SweepConfig()
    recs = sweep_sequence("synthetic", pr, gt, tel, states, cfg)
    assert recs, "selftest produced no records (window logic broken?)"
    for r in recs:
        assert_record_schema(r)
    print(f"[selftest] {len(recs)} records, schema OK", file=sys.stderr)

    # --- behavioural checks on the approximation ---
    # On a smooth-motion loss, MOTION_BRIDGE (extrapolating the pre-loss velocity)
    # must earn a clearly positive ΔIoU on at least one windowed frame — that is
    # the whole point of the bridge proxy.
    bn = Action.MOTION_BRIDGE.name.lower()
    bridge_pos = [r for r in recs if r["action_gain"][bn] > cfg.recover_margin]
    assert bridge_pos, "motion_bridge never beat HOLD on a smooth-motion loss (approx broken)"
    # ... and those frames must be flagged recoverable_by_bridge.
    assert any(r["recoverable_by_bridge"] for r in recs), \
        "no frame flagged recoverable_by_bridge on a smooth loss"
    # relocate must NOT be credited (no secondary peak in telemetry).
    for r in recs:
        rg = r["action_gain"][Action.RELOCATE.name.lower()]
        assert rg <= 1e-9, f"relocate credited with no secondary peak: {rg}"
    # Once IoU fully collapses, GLOBAL_SEARCH (re-acquire anywhere) should be the
    # best proxy action — sanity-check the loss arm of the approximation.
    collapsed = [r for r in recs if r["passive_iou"] <= 1e-6]
    assert collapsed and all(r["best_action"] == Action.GLOBAL_SEARCH.name.lower()
                             for r in collapsed), \
        "global_search not best when passive IoU has collapsed (approx broken)"

    # Second mini-case: a HEALTHY frame should be do_not_act (nothing beats hold).
    pr2 = gt.copy()                          # perfect tracking
    tel2 = [{"frame_idx": i, "sm_n_secondary": 0.0, "sm_local_top2_ratio": 0.0} for i in range(n)]
    st2 = [{"frame_idx": i, "derived_state": 0} for i in range(n)]
    # force a window by dipping one frame just under risk_iou
    pr2[6] = gt[6] + np.array([18.0, 0.0, 0.0, 0.0])   # partial drift -> at-risk, recoverable
    recs2 = sweep_sequence("synthetic_healthy", pr2, gt, tel2, st2, cfg)
    for r in recs2:
        assert_record_schema(r)
    print(f"[selftest] healthy-case {len(recs2)} records, schema OK", file=sys.stderr)

    # Third mini-case: a loss WITH a usable secondary peak -> RELOCATE credited.
    pr3 = gt.copy()
    for i in range(5, n):
        pr3[i] = gt[5].copy()                # stuck box (loss)
    tel3 = []
    st3 = []
    for i in range(n):
        ds = 0 if i < 5 else 2
        # advertise a strong secondary peak once lost (top2_ratio above relocate_ratio)
        tel3.append({"frame_idx": i, "sm_n_secondary": 0.0 if ds == 0 else 2.0,
                     "sm_local_top2_ratio": 0.0 if ds == 0 else 0.6})
        st3.append({"frame_idx": i, "derived_state": ds})
    recs3 = sweep_sequence("synthetic_relocate", pr3, gt, tel3, st3, cfg)
    for r in recs3:
        assert_record_schema(r)
    assert any(r["recoverable_by_relocate"] for r in recs3), \
        "relocate not credited even with a strong secondary peak (approx broken)"
    print(f"[selftest] relocate-case {len(recs3)} records, schema OK", file=sys.stderr)

    sample = recs[len(recs) // 2]
    print("[selftest] sample record:", file=sys.stderr)
    print(json.dumps(sample, indent=2), file=sys.stderr)

    if out_path is not None:
        with open(out_path, "w") as fh:
            for r in recs + recs2 + recs3:
                fh.write(json.dumps(r) + "\n")
        print(f"[selftest] wrote {len(recs) + len(recs2) + len(recs3)} records -> {out_path}",
              file=sys.stderr)

    print("[selftest] PASS", file=sys.stderr)
    return 0


# ---------------------------------------------------------------------------
# Real sweep over a passive run dir (reuses la_smoke loaders).
# ---------------------------------------------------------------------------
def run_sweep(passive_dir: Path, dataset: str, out_path: Path,
              seqs: Optional[list[str]], cfg: SweepConfig) -> None:
    # Imported lazily so --selftest needs NO dataset / registry.
    _argv = sys.argv
    sys.argv = [sys.argv[0]]
    import csc_uav_tracking  # noqa: F401  (registers datasets)
    import la_smoke as ls
    sys.argv = _argv

    print(f"loading {dataset} ...", file=sys.stderr)
    idx = ls.build_index(dataset)
    names: Iterable[str]
    if seqs:
        names = seqs
    else:
        names = sorted(p.stem for p in (passive_dir / "predictions").glob("*.txt"))

    pred_dir = passive_dir / "predictions"
    state_dir = passive_dir / "states"
    tel_dir = passive_dir / "telemetry"

    total = 0
    n_seqs = 0
    with open(out_path, "w") as fh:
        for name in names:
            seq = idx.get(name)
            if seq is None:
                print(f"  {name}: not in {dataset}, skip", file=sys.stderr)
                continue
            pf = pred_dir / f"{name}.txt"
            if not pf.exists():
                print(f"  {name}: no predictions, skip", file=sys.stderr)
                continue
            gt = ls.gt_array(seq)
            pr = ls.read_preds(pf)
            n = min(len(pr), len(gt))
            if n < 2:
                continue
            tel = read_telemetry(tel_dir / f"{name}.jsonl", n)
            states = read_states(state_dir / f"{name}.jsonl", n)
            recs = sweep_sequence(name, pr[:n], gt[:n], tel, states, cfg)
            for r in recs:
                assert_record_schema(r)     # cheap guard; keep output honest
                fh.write(json.dumps(r) + "\n")
            total += len(recs)
            n_seqs += 1
            print(f"  {name}: {len(recs)} windowed frames", file=sys.stderr)
    print(f"\nwrote {total} action-gain records over {n_seqs} sequences -> {out_path}",
          file=sys.stderr)


def build_argparser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--passive_dir", default=None,
                    help="passive run dir (predictions/ states/ telemetry/)")
    ap.add_argument("--dataset", default="uav123", help="dataset for la_smoke.build_index")
    ap.add_argument("--out", default=None, help="output JSONL path")
    ap.add_argument("--seqs", nargs="*", default=None, help="restrict to these sequences")
    ap.add_argument("--selftest", action="store_true",
                    help="run a tiny synthetic example with NO dataset and assert the schema")
    # Tunable thresholds (documented in SweepConfig).
    ap.add_argument("--loss_iou", type=float, default=SweepConfig.loss_iou)
    ap.add_argument("--risk_iou", type=float, default=SweepConfig.risk_iou)
    ap.add_argument("--pre_window", type=int, default=SweepConfig.pre_window)
    ap.add_argument("--recover_margin", type=float, default=SweepConfig.recover_margin)
    ap.add_argument("--relocate_ratio", type=float, default=SweepConfig.relocate_ratio)
    ap.add_argument("--widen_frac", type=float, default=SweepConfig.widen_frac)
    return ap


def main() -> int:
    args = build_argparser().parse_args()
    cfg = SweepConfig(
        loss_iou=args.loss_iou,
        risk_iou=args.risk_iou,
        pre_window=args.pre_window,
        recover_margin=args.recover_margin,
        relocate_ratio=args.relocate_ratio,
        widen_frac=args.widen_frac,
    )

    if args.selftest:
        return _selftest(Path(args.out) if args.out else None)

    if not args.passive_dir:
        raise SystemExit("need --passive_dir (or --selftest)")
    if not args.out:
        raise SystemExit("need --out <path.jsonl>")
    passive_dir = Path(args.passive_dir)
    if not (passive_dir / "predictions").is_dir():
        raise SystemExit(f"{passive_dir} has no predictions/ subdir")
    run_sweep(passive_dir, args.dataset, Path(args.out), args.seqs, cfg)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
